apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cvmfs-gxy-cloud-pvc
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: cvmfs-gxy-cloud
