nameOverride: ""
fullnameOverride: ""

configs: {}

cloneJob:
  image: google/cloud-sdk:latest
  command: gcloud auth activate-service-account --key-file=/mnt/configs/sa_key.json && gsutil rsync -d /mnt/cloud.galaxyproject.org gs://cloud-cvmfs/

