name: Clone CVMFS repository cloud.galaxyproject.org to a Google bucket
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}
jobs:
  clone:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    container:
      image: galaxy/cvmfs-client:latest
      options: --privileged

    steps:
      - uses: 'actions/checkout@v3'

      - id: Auth
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: 'projects/526897014808/locations/global/workloadIdentityPools/galaxy-tests-identity-pool'
          service_account: 'galaxy-tests-repo-actions-sa@anvil-and-terra-development.iam.gserviceaccount.com'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Run clone script
        run: sh clone.sh
