name: Clone CVMFS repository cloud.galaxyproject.org to a Google bucket
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}
jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Start K8s locally
        uses: jupyterhub/action-k3s-helm@v2
        with:
          k3s-version: v1.19.16+k3s1  # releases: https://github.com/k3s-io/k3s/tags; must use 1.19 b/c of CVMFS-CSI
          metrics-enabled: false
          traefik-enabled: false
        continue-on-error: true

      - name: Get logs
        run: |
          cat /var/log/syslog
          journalctl -u k3s.service
